const Mongoose = require('mongoose')
const clienteSchema = new Mongoose.Schema({
    CAP: Number,
    CAP2: String,
    Categoria: String,
    ClienteID : Number,
    CodiceAgenzia : Number,
    CodiceCliente : Number,
    CodiceCollab : String,
    CodiceFiscale : String,
    Cognome : String,
    Contattabile : Number,
    ContattoID : String,
    DataAggiornamentoSaldo : String,
    DataNascita : String,
    DataOraRichiamoABreve__NOT_USED : String,
    DataRichiamo : String,
    Denominazione : String,
    Email : String,
    Fax : String,
    IBAN : String,
    ImportoRata : String,
    ImportoRataStorica :  Number,
    ImportoSaldoAttualizzato :  Number,
    ImportoSaldoContabile : String,
    ImportoSaldoStorico :  Number,
    Indirizzo : String,
    Indirizzo2 : String,
    Località : String,
    Località2 : String,
    Nome : String,
    Note : String,
    Operatore : String,
    PartitaIVA : String,
    Provincia : String,
    Provincia2 : String,
    Sesso : String,
    Telefono1 : String,
    Telefono2 : String,
    Telefono3 : String,
    TipoCliente : String,
    TipoContoStorico : String,
    TipoPagamentoStorico : String,
    TipoRagioneSociale : String,
    TitoloAcc : String
},
{
    collection : 'Clienti'
})

const Cliente = Mongoose.model('cliente', clienteSchema, 'Clienti');
module.exports = Cliente;